version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: jobportaldbuser
      POSTGRES_PASSWORD: 35S_Ith??h3trEs8ucr@
      POSTGRES_DB: JobPortalDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app_network
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - app_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobportal_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Database=JobPortalDb;Username=jobportaldbuser;Password=35S_Ith??h3trEs8ucr@
      - ElasticSearch__Uri=http://elasticsearch:9200
      - Redis__ConnectionString=redis:6379
    ports:
      - "5000:80"
    depends_on:
      - postgres
      - elasticsearch
      - redis
    networks:
      - app_network

volumes:
  postgres_data:
  elasticsearch_data:
  redis_data:
