//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobPortal.Common.Resources.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres 200 karakterden uzun olamaz..
        /// </summary>
        internal static string AddressMaxLength {
            get {
                return ResourceManager.GetString("AddressMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres zorunludur..
        /// </summary>
        internal static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yan haklar 200 karakterden uzun olamaz..
        /// </summary>
        internal static string BenefitsMaxLength {
            get {
                return ResourceManager.GetString("BenefitsMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket adı 100 karakterden uzun olamaz..
        /// </summary>
        internal static string CompanyNameMaxLength {
            get {
                return ResourceManager.GetString("CompanyNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket adı zorunludur..
        /// </summary>
        internal static string CompanyNameRequired {
            get {
                return ResourceManager.GetString("CompanyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket bulunamadı..
        /// </summary>
        internal static string CompanyNotFound {
            get {
                return ResourceManager.GetString("CompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama 1000 karakterden uzun olamaz..
        /// </summary>
        internal static string DescriptionMaxLength {
            get {
                return ResourceManager.GetString("DescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama en az 10 karakter olmalıdır..
        /// </summary>
        internal static string DescriptionMinLength {
            get {
                return ResourceManager.GetString("DescriptionMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama zorunludur..
        /// </summary>
        internal static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu e-posta ile kayıtlı bir kullanıcı zaten var..
        /// </summary>
        internal static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta adresi zorunludur..
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma türü 50 karakterden uzun olamaz..
        /// </summary>
        internal static string EmploymentTypeMaxLength {
            get {
                return ResourceManager.GetString("EmploymentTypeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlan bitiş tarihi gelecekte olmalıdır..
        /// </summary>
        internal static string ExpirationDateFuture {
            get {
                return ResourceManager.GetString("ExpirationDateFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz e-posta formatı..
        /// </summary>
        internal static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz e-posta veya şifre..
        /// </summary>
        internal static string InvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("InvalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz telefon numarası formatı..
        /// </summary>
        internal static string InvalidPhoneNumberFormat {
            get {
                return ResourceManager.GetString("InvalidPhoneNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş ilanı oluşturuldu, ancak Elasticsearch&apos;e eklenemedi..
        /// </summary>
        internal static string JobCreatedFailedElasticsearch {
            get {
                return ResourceManager.GetString("JobCreatedFailedElasticsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş ilanı başarıyla oluşturuldu ve Elasticsearch&apos;e eklendi..
        /// </summary>
        internal static string JobCreatedSuccessfully {
            get {
                return ResourceManager.GetString("JobCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş ilanı başarıyla silindi..
        /// </summary>
        internal static string JobDeletedSuccessfully {
            get {
                return ResourceManager.GetString("JobDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlan bulunamadı..
        /// </summary>
        internal static string JobNotFound {
            get {
                return ResourceManager.GetString("JobNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş ilanı yayınlama limiti aşıldı..
        /// </summary>
        internal static string JobPostingLimitExceeded {
            get {
                return ResourceManager.GetString("JobPostingLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş ilanı limiti 0&apos;dan büyük olmalıdır..
        /// </summary>
        internal static string JobPostingLimitGreaterThan {
            get {
                return ResourceManager.GetString("JobPostingLimitGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş ilanı başarıyla getirildi..
        /// </summary>
        internal static string JobRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("JobRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş ilanları bulundu..
        /// </summary>
        internal static string JobsFound {
            get {
                return ResourceManager.GetString("JobsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş ilanları başarıyla getirildi..
        /// </summary>
        internal static string JobsRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("JobsRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş ilanı güncellendi, ancak Elasticsearch&apos;te güncellenemedi..
        /// </summary>
        internal static string JobUpdatedFailedElasticsearch {
            get {
                return ResourceManager.GetString("JobUpdatedFailedElasticsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş ilanı başarıyla güncellendi ve Elasticsearch&apos;te güncellendi..
        /// </summary>
        internal static string JobUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("JobUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş başarılı..
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş ilanı bulunamadı..
        /// </summary>
        internal static string NoJobsFound {
            get {
                return ResourceManager.GetString("NoJobsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem sırasında hata oluştu.
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem başarılı.
        /// </summary>
        internal static string OperationSuccess {
            get {
                return ResourceManager.GetString("OperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre başarıyla yenilendi..
        /// </summary>
        internal static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreler eşleşmiyor..
        /// </summary>
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon numarası zorunludur..
        /// </summary>
        internal static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozisyon adı 100 karakterden uzun olamaz..
        /// </summary>
        internal static string PositionMaxLength {
            get {
                return ResourceManager.GetString("PositionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozisyon adı zorunludur..
        /// </summary>
        internal static string PositionRequired {
            get {
                return ResourceManager.GetString("PositionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalite skoru 0 ile 5 arasında olmalıdır..
        /// </summary>
        internal static string QualityScoreRange {
            get {
                return ResourceManager.GetString("QualityScoreRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sakıncalı kelime başarıyla eklendi..
        /// </summary>
        internal static string RestrictedWordAddedSuccessfully {
            get {
                return ResourceManager.GetString("RestrictedWordAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlan açıklaması sakıncalı kelime içeriyor: {word}..
        /// </summary>
        internal static string RestrictedWordInDescription {
            get {
                return ResourceManager.GetString("RestrictedWordInDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sakıncalı kelime başarıyla silindi..
        /// </summary>
        internal static string RestrictedWordRemovedSuccessfully {
            get {
                return ResourceManager.GetString("RestrictedWordRemovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sakıncalı kelimeler başarıyla getirildi..
        /// </summary>
        internal static string RestrictedWordsRetrieved {
            get {
                return ResourceManager.GetString("RestrictedWordsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı başarıyla silindi..
        /// </summary>
        internal static string UserDeletedSuccess {
            get {
                return ResourceManager.GetString("UserDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı 100 karakterden uzun olamaz..
        /// </summary>
        internal static string UserNameMaxLength {
            get {
                return ResourceManager.GetString("UserNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı zorunludur..
        /// </summary>
        internal static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı bulunamadı..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı başarıyla kayıt edildi..
        /// </summary>
        internal static string UserRegisteredSuccess {
            get {
                return ResourceManager.GetString("UserRegisteredSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcılar başarıyla getirildi..
        /// </summary>
        internal static string UsersRetrievedSuccess {
            get {
                return ResourceManager.GetString("UsersRetrievedSuccess", resourceCulture);
            }
        }
    }
}
